# Базовый образ Node.js
FROM node:22

# Устанавливаем рабочую директорию
WORKDIR /src

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости, игнорируя optional dependencies
RUN npm install --no-optional

# Устанавливаем Ionic CLI глобально
RUN npm install -g @ionic/cli

# Копируем исходный код проекта
COPY . .

# Открываем порт 8100 для Ionic (по умолчанию `ionic serve` использует порт 8100)
EXPOSE 8100

# Запускаем приложение в режиме разработки
CMD ["ionic", "serve", "--host=0.0.0.0"]
