# Используем официальный Node образ для установки зависимостей
FROM node:20

# Устанавливаем Ionic CLI глобально
RUN npm install -g @ionic/cli

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем package.json и package-lock.json для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта в контейнер
COPY . .

# Открываем порт 8100 для доступа к приложению
EXPOSE 8100

# Запускаем Ionic сервер с включенным polling
CMD ["ionic", "serve", "--host", "0.0.0.0", "--port", "8100"]
